export const PRODUCTS_GET_ALL_REQUESTED = 'PRODUCTS_GET_ALL_REQUESTED';
export const PRODUCTS_GET_ALL_SUCCEEDED = 'PRODUCTS_GET_ALL_SUCCEEDED';
export const PRODUCTS_GET_ALL_FAILED = 'PRODUCTS_GET_ALL_FAILED';
