export const USER_ON_SUBMIT_ORDER_REQUESTED = 'USER_ON_SUBMIT_ORDER_REQUESTED';
export const USER_ON_SUBMIT_ORDER_SUCCEEDED = 'USER_ON_SUBMIT_ORDER_SUCCEEDED';
export const USER_ON_SUBMIT_ORDER_FAILED = 'USER_ON_SUBMIT_ORDER_FAILED';

export const USER_ON_GET_ORDER_STATUS_REQUESTED = 'USER_ON_GET_ORDER_STATUS_REQUESTED';
export const USER_ON_GET_ORDER_STATUS_SUCCEEDED = 'USER_ON_GET_ORDER_STATUS_SUCCEEDED';
export const USER_ON_GET_ORDER_STATUS_FAILED = 'USER_ON_GET_ORDER_STATUS_FAILED';

